# Matter SDK Include Paths
# Auto-generated by scripts/gen_matter_includes.sh — do not edit manually
# Supports both host and cross-compilation builds

MATTER_SDK_ROOT = $(shell pwd)/deps/connectedhomeip

# Device profile: light
# Example app: lighting-app
# Common target: lighting-common
MATTER_PROFILE_NAME = light

# Detect target platform dynamically
ifeq ($(CROSSCOMPILE),1)
    ifeq ($(findstring aarch64,$(TARGET_ARCH)),aarch64)
        MATTER_TARGET = linux-arm64-light
    else ifeq ($(findstring arm,$(TARGET_ARCH)),arm)
        MATTER_TARGET = linux-arm-light
    else
        MATTER_TARGET = linux-x64-light
    endif
else
    UNAME_S := $(shell uname -s)
    UNAME_M := $(shell uname -m)

    ifeq ($(UNAME_S),Darwin)
        ifeq ($(UNAME_M),arm64)
            MATTER_TARGET = darwin-arm64-light
        else
            MATTER_TARGET = darwin-x64-light
        endif
    else ifeq ($(UNAME_S),Linux)
        ifeq ($(UNAME_M),aarch64)
            MATTER_TARGET = linux-arm64-light
        else ifeq ($(UNAME_M),armv7l)
            MATTER_TARGET = linux-arm-light
        else
            MATTER_TARGET = linux-x64-light
        endif
    else
        MATTER_TARGET = linux-x64-light
    endif
endif

MATTER_BUILD_DIR = $(MATTER_SDK_ROOT)/out/$(MATTER_TARGET)

# Required defines for Matter SDK headers
MATTER_DEFINES = -DCHIP_HAVE_CONFIG_H=1 -DNDEBUG
ifeq ($(MATTER_DEBUG),1)
    MATTER_DEFINES += -DCHIP_CONFIG_VERBOSE_VERIFY_OR_DIE=1
endif

# Generated includes from build (MUST come first so config headers override defaults)
MATTER_INCLUDES = \
    -I$(MATTER_BUILD_DIR)/gen/include \
    -I$(MATTER_BUILD_DIR)/gen \
    -I$(MATTER_BUILD_DIR)/gen/third_party/connectedhomeip/examples/lighting-app/lighting-common \
    -I$(MATTER_BUILD_DIR)/gen/third_party/connectedhomeip/examples/lighting-app/lighting-common/zapgen

# Pre-generated ZAP headers (app-common cluster definitions)
MATTER_INCLUDES += \
    -I$(MATTER_SDK_ROOT)/zzz_generated/app-common

# Core Matter SDK includes
MATTER_INCLUDES += \
    -I$(MATTER_SDK_ROOT)/src \
    -I$(MATTER_SDK_ROOT)/src/include \
    -I$(MATTER_SDK_ROOT)/config/standalone \
    -I$(MATTER_SDK_ROOT)/examples \
    -I$(MATTER_SDK_ROOT)/examples/platform/linux \
    -I$(MATTER_SDK_ROOT)/examples/providers \
    -I$(MATTER_SDK_ROOT)/examples/lighting-app/lighting-common/include \
    -I$(MATTER_SDK_ROOT)/examples/common/tracing

# Third-party includes
MATTER_INCLUDES += \
    -I$(MATTER_SDK_ROOT)/third_party/nlassert/repo/include \
    -I$(MATTER_SDK_ROOT)/third_party/nlio/repo/include \
    -I$(MATTER_SDK_ROOT)/third_party/nlfaultinjection/include \
    -I$(MATTER_SDK_ROOT)/third_party/jsoncpp/repo/include \
    -I$(MATTER_SDK_ROOT)/third_party/boringssl/repo/src/include \
    -I$(MATTER_SDK_ROOT)/third_party/inipp/repo/inipp \
    -I$(MATTER_SDK_ROOT)/third_party/perfetto/repo/sdk \
    -I$(MATTER_SDK_ROOT)/src/tracing/perfetto/include

# Pigweed includes
PIGWEED_ROOT = $(MATTER_SDK_ROOT)/third_party/pigweed/repo
MATTER_INCLUDES += \
    -I$(PIGWEED_ROOT)/pw_assert/public \
    -I$(PIGWEED_ROOT)/pw_assert/assert_compatibility_public_overrides \
    -I$(PIGWEED_ROOT)/pw_base64/public \
    -I$(PIGWEED_ROOT)/pw_bytes/public \
    -I$(PIGWEED_ROOT)/pw_containers/public \
    -I$(PIGWEED_ROOT)/pw_function/public \
    -I$(PIGWEED_ROOT)/pw_log/public \
    -I$(PIGWEED_ROOT)/pw_metric/public \
    -I$(PIGWEED_ROOT)/pw_numeric/public \
    -I$(PIGWEED_ROOT)/pw_polyfill/public \
    -I$(PIGWEED_ROOT)/pw_preprocessor/public \
    -I$(PIGWEED_ROOT)/pw_result/public \
    -I$(PIGWEED_ROOT)/pw_span/public \
    -I$(PIGWEED_ROOT)/pw_status/public \
    -I$(PIGWEED_ROOT)/pw_string/public \
    -I$(PIGWEED_ROOT)/pw_tokenizer/public \
    -I$(PIGWEED_ROOT)/pw_toolchain/public \
    -I$(PIGWEED_ROOT)/pw_varint/public \
    -I$(PIGWEED_ROOT)/third_party/fuchsia/repo/sdk/lib/stdcompat/include

# Extra object files from lighting-app build (not in libCHIP.a)
MATTER_EXTRA_OBJS = \
    $(MATTER_BUILD_DIR)/obj/chip-lighting-app.LightingAppCommandDelegate.cpp.o \
    $(MATTER_BUILD_DIR)/obj/chip-lighting-app.main.cpp.o \
    $(MATTER_BUILD_DIR)/obj/gen/third_party/connectedhomeip/examples/lighting-app/lighting-common/app/lighting-common_codegen.callback-stub.cpp.o \
    $(MATTER_BUILD_DIR)/obj/gen/third_party/connectedhomeip/examples/lighting-app/lighting-common/app/lighting-common_codegen.cluster-callbacks.cpp.o \
    $(MATTER_BUILD_DIR)/obj/gen/third_party/connectedhomeip/examples/lighting-app/lighting-common/zapgen/zap-generated/lighting-common_zapgen.CodeDrivenInitShutdown.cpp.o \
    $(MATTER_BUILD_DIR)/obj/gen/third_party/connectedhomeip/examples/lighting-app/lighting-common/zapgen/zap-generated/lighting-common_zapgen.IMClusterCommandHandler.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/commandline.TracingCommandLineArgument.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/decoder/bdx/trace_handlers_decoder.Decoder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/decoder/echo/trace_handlers_decoder.Decoder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/decoder/interaction_model/trace_handlers_decoder.Decoder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/decoder/interaction_model/trace_handlers_decoder.DecoderCustomLog.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/decoder/logging/trace_handlers_decoder.Log.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/decoder/logging/trace_handlers_decoder.ToCertificateString.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/decoder/secure_channel/trace_handlers_decoder.Decoder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/decoder/trace_handlers_decoder.TraceDecoderProtocols.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/decoder/udc/trace_handlers_decoder.Decoder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/trace_handlers.TraceHandlers.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/common/tracing/trace_handlers_decoder.TraceDecoder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/lighting-app/lighting-common/src/lighting-manager.LightingManager.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/platform/linux/app-main.AppMain.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/platform/linux/app-main.CommissionableInit.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/platform/linux/app-main.NamedPipeCommands.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/platform/linux/app-options.Options.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/platform/linux/commissioner-main.CommissionerMain.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/platform/linux/linux-commissionable-data-provider.LinuxCommissionableDataProvider.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/platform/linux/testing/app-options.CustomCSRResponse.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/examples/platform/linux/testing/app-options.CustomCSRResponseOperationalKeyStore.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.ArrayBuilder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.ArrayParser.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.AttributeDataIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.AttributeDataIBs.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.AttributePathIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.AttributePathIBs.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.AttributeReportIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.AttributeReportIBs.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.AttributeStatusIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.AttributeStatusIBs.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.Builder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.ClusterPathIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.CommandDataIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.CommandPathIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.CommandStatusIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.DataVersionFilterIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.DataVersionFilterIBs.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.EventDataIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.EventFilterIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.EventFilterIBs.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.EventPathIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.EventPathIBs.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.EventReportIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.EventReportIBs.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.EventStatusIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.InvokeRequestMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.InvokeRequests.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.InvokeResponseIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.InvokeResponseIBs.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.InvokeResponseMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.ListBuilder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.ListParser.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.MessageBuilder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.MessageDefHelper.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.MessageParser.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.Parser.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.ReadRequestMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.ReportDataMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.StatusIB.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.StatusResponseMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.StructBuilder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.StructParser.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.SubscribeRequestMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.SubscribeResponseMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.TimedRequestMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.WriteRequestMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/MessageDef/MessageDef.WriteResponseMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/attribute-persistence.SafeAttributePersistenceProvider.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/access-control-server/access-control-server.access-control-cluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/access-control-server/arl-encoder.ArlEncoder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/access-control-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/administrator-commissioning-server/administrator-commissioning-server.AdministratorCommissioningCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/administrator-commissioning-server/administrator-commissioning-server.AdministratorCommissioningLogic.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/administrator-commissioning-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/basic-information/basic-information.BasicInformationCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/basic-information/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/color-control-server/lighting-common.color-control-server.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/descriptor/descriptor.DescriptorCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/descriptor/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/diagnostic-logs-server/diagnostic-logs-server.BDXDiagnosticLogsProvider.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/diagnostic-logs-server/diagnostic-logs-server.DiagnosticLogsCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/diagnostic-logs-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/ethernet-network-diagnostics-server/ethernet-network-diagnostics-server.EthernetDiagnosticsCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/ethernet-network-diagnostics-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/general-commissioning-server/general-commissioning-server.GeneralCommissioningCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/general-commissioning-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/general-diagnostics-server/general-diagnostics-server.GeneralDiagnosticsCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/general-diagnostics-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/group-key-mgmt-server/group-key-mgmt-server.GroupKeyManagementCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/group-key-mgmt-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/groups-server/lighting-common.groups-server.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/identify-server/identify-server.IdentifyCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/identify-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/level-control/codegen/lighting-common.level-control.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/network-commissioning/lighting-common.CodegenInstance.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/network-commissioning/network-commissioning.NetworkCommissioningCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/network-commissioning/thread-response-encoding.ThreadScanResponse.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/network-commissioning/wifi-response-encoding.WifiScanResponse.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/on-off-server/codegen/lighting-common.level-control-integration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/on-off-server/codegen/lighting-common.mode-base-integration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/on-off-server/codegen/lighting-common.mode-select-integration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/on-off-server/codegen/lighting-common.on-off-server.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/on-off-server/codegen/lighting-common.scenes-integration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/operational-credentials-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/operational-credentials-server/operational-credentials-server.OperationalCredentialsCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/ota-requestor/lighting-common.BDXDownloader.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/ota-requestor/lighting-common.DefaultOTARequestor.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/ota-requestor/lighting-common.DefaultOTARequestorDriver.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/ota-requestor/lighting-common.DefaultOTARequestorStorage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/ota-requestor/lighting-common.ExtendedOTARequestorDriver.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/ota-requestor/lighting-common.OTATestEventTriggerHandler.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/ota-requestor/lighting-common.ota-requestor-server.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/software-diagnostics-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/software-diagnostics-server/software-diagnostics-server.SoftwareDiagnosticsLogic.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/software-diagnostics-server/software-fault-listener.software-fault-listener.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/thread-network-diagnostics-server/lighting-common.ThreadNetworkDiagnosticsCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/thread-network-diagnostics-server/lighting-common.ThreadNetworkDiagnosticsProvider.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/user-label-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/user-label-server/user-label-server.UserLabelCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/wifi-network-diagnostics-server/lighting-common.CodegenIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/clusters/wifi-network-diagnostics-server/wifi-network-diagnostics-server.WiFiNetworkDiagnosticsCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/command-handler-impl.CommandHandlerImpl.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/command-handler-interface.CommandHandlerInterfaceRegistry.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/command-handler.CommandHandler.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/data-model-provider/data-model-provider.ActionReturnStatus.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/data-model-provider/data-model-provider.EventsGenerator.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/data-model-provider/data-model-provider.MetadataLookup.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/data-model-provider/data-model-provider.ProviderMetadataTree.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/data-model/data-model.FabricScopedPreEncodedValue.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/data-model/data-model.PreEncodedValue.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/data-model/encode-decode.StructDecodeIterator.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/data-model/encode-decode.WrappedStructEncoder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/global-attributes.GlobalAttributes.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/path-expansion.AttributePathExpandIterator.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/persistence/default.DefaultAttributePersistenceProvider.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/persistence/persistence.AttributePersistence.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/persistence/persistence.String.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/persistence/singleton.AttributePersistenceProviderInstance.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/reporting/lighting-common.reporting.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/server-cluster/registry.ServerClusterInterfaceRegistry.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/server-cluster/registry.SingleEndpointServerClusterRegistry.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/server-cluster/server-cluster.AttributeListBuilder.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/server-cluster/server-cluster.DefaultServerCluster.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/server-cluster/server-cluster.ServerClusterExtension.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/server-cluster/server-cluster.ServerClusterInterface.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/status-response.StatusResponse.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/storage-wrapper.StorageDelegateWrapper.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/tests/suites/credentials/dac_provider.TestHarnessDACProvider.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/util/callbacks.MatterCallbacks.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/util/lighting-common.DataModelHandler.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/util/lighting-common.attribute-storage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/util/lighting-common.attribute-table.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/util/lighting-common.ember-io-storage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/util/lighting-common.generic-callback-stubs.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/util/lighting-common.privilege-storage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/util/lighting-common.util.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/util/types.attribute-metadata.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/util/types.ember-strings.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/credentials/jcm/jcm.TrustVerification.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/credentials/jcm/jcm.VendorIdVerificationClient.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/crypto/cryptopal_openssl.CHIPCryptoPALOpenSSL.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/crypto/cryptopal_openssl.P256KeyPairOpenSSL.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/data-model-providers/codegen/lighting-common.ClusterIntegration.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/data-model-providers/codegen/lighting-common.CodegenDataModelProvider.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/data-model-providers/codegen/lighting-common.CodegenDataModelProvider_Read.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/data-model-providers/codegen/lighting-common.CodegenDataModelProvider_Write.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/data-model-providers/codegen/lighting-common.EmberAttributeDataBuffer.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/data-model-providers/codegen/lighting-common.Instance.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/core/error.CHIPError.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/core/error.ErrorStr.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/dnssd/minimal_mdns/address_policy.AddressPolicy.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/dnssd/naming.ServiceNaming.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/support/arg_parser.CHIPArgParser.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/support/logging/text_only_logging.TextOnlyLogging.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/support/memory.CHIPMem-Malloc.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/support/memory.CHIPMem.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/support/memory.CHIPPlatformMemory.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/platform/logging/impl/stdio.Stdio.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/protocols/secure_channel/check-in-counter.CheckInCounter.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/protocols/secure_channel/check-in-message.CheckinMessage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/setup_payload/additional_data_payload.AdditionalDataPayloadGenerator.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/setup_payload/additional_data_payload.AdditionalDataPayloadParser.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/setup_payload/onboarding-codes-utils.OnboardingCodesUtil.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/tracing/perfetto/event_storage.event_storage.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/tracing/perfetto/file_output.file_output.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/tracing/perfetto/simple_initialization.simple_initialize.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/third_party/jsoncpp/repo/src/lib_json/jsoncpp.json_reader.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/third_party/jsoncpp/repo/src/lib_json/jsoncpp.json_value.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/third_party/jsoncpp/repo/src/lib_json/jsoncpp.json_writer.cpp.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/third_party/perfetto/repo/sdk/sdk.perfetto.cc.o \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/zzz_generated/app-common/app-common/zap-generated/attributes/lighting-common.Accessors.cpp.o

# Matter SDK static libraries
MATTER_STATIC_LIBS = \
    $(MATTER_BUILD_DIR)/lib/libCHIP.a \
    $(MATTER_BUILD_DIR)/lib/libMatterAllClustersDeviceInfoProviderExample.a \
    $(MATTER_BUILD_DIR)/lib/libMatterDeviceInfoProviderExample.a \
    $(MATTER_BUILD_DIR)/lib/libnlfaultinjection.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/access/lib/libaccess.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/common/lib/libClusterObjects.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/lib/attribute-access.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/lib/interaction-model.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/lib/libCHIPDataModel.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/app/server/lib/libCHIPAppServer.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/ble/lib/libBleLayer.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/controller/lib/libChipController.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/credentials/lib/libCredentials.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/crypto/lib/libChipCrypto.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/inet/lib/libInetLayer.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/address_resolve/lib/address_resolve.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/asn1/lib/libASN1.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/core/lib/libChipCore.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/dnssd/lib/dnssd.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/dnssd/minimal_mdns/core/lib/core.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/dnssd/minimal_mdns/lib/default_policy.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/dnssd/minimal_mdns/lib/minimal_mdns.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/dnssd/minimal_mdns/records/lib/records.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/dnssd/minimal_mdns/responders/lib/responders.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/lib/support/lib/libSupportLayer.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/messaging/lib/libMessagingLayer.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/platform/Linux/dbus/bluez/lib/bluez.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/platform/Linux/dbus/openthread/lib/openthread.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/platform/Linux/dbus/wpa/lib/wpa.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/platform/Linux/lib/Linux.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/platform/lib/libDeviceLayer.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/protocols/bdx/lib/libBdx.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/protocols/interaction_model/lib/libInteractionModel.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/protocols/lib/libChipProtocols.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/protocols/secure_channel/lib/libSecureChannel.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/protocols/secure_channel/lib/libSecureChannelTypes.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/setup_payload/lib/libSetupPayload.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/system/lib/libSystemLayer.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/tracing/json/lib/json.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/tracing/lib/tracing.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/tracing/perfetto/lib/perfetto.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/transport/lib/libTransportLayer.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/transport/raw/lib/libRawTransport.a \
    $(MATTER_BUILD_DIR)/obj/third_party/connectedhomeip/src/wifipaf/lib/libWiFiPAFLayer.a

MATTER_LIBS = -Wl,--start-group $(MATTER_STATIC_LIBS) -Wl,--end-group

# Platform-specific libraries
ifeq ($(shell uname -s),Darwin)
    ifeq ($(CROSSCOMPILE),1)
        # Cross-compiling from Darwin to Linux (Nerves)
        MATTER_LIBS += -latomic -ldl -lpthread -lrt -lssl -lcrypto -lgio-2.0 -lgobject-2.0 -lglib-2.0
    else
        # Native Darwin build - no --start-group support, use single lib
        MATTER_LIBS = -L$(MATTER_BUILD_DIR)/lib -lCHIP
        MATTER_LIBS += -framework CoreFoundation -framework CoreBluetooth -framework IOKit -framework Security
    endif
else
    # Linux host or target
    MATTER_LIBS += -latomic -ldl -lpthread -lrt -lssl -lcrypto -lgio-2.0 -lgobject-2.0 -lglib-2.0
endif

# Cross-compilation sysroot includes (D-Bus, GLib, BlueZ headers)
ifeq ($(CROSSCOMPILE),1)
    ifdef NERVES_SDK_SYSROOT
        MATTER_INCLUDES += -I$(NERVES_SDK_SYSROOT)/usr/include/dbus-1.0
        MATTER_INCLUDES += -I$(NERVES_SDK_SYSROOT)/usr/lib/dbus-1.0/include
        MATTER_INCLUDES += -I$(NERVES_SDK_SYSROOT)/usr/include/glib-2.0
        MATTER_INCLUDES += -I$(NERVES_SDK_SYSROOT)/usr/lib/glib-2.0/include
    endif
endif
