#!/bin/bash
# Generate matter_sdk_includes.mk from Matter SDK build output
#
# Usage: scripts/gen_matter_includes.sh <build_dir> <profile_name>
#
# This script reads the linked_objects.txt and linked_libs.txt manifests
# generated by docker/build.sh and produces a matter_sdk_includes.mk file
# with the correct object files, libraries, and include paths for the
# selected device profile.
set -e

BUILD_DIR="$1"
PROFILE_NAME="$2"
OUTPUT_FILE="${3:-matter_sdk_includes.mk}"

if [ -z "$BUILD_DIR" ] || [ -z "$PROFILE_NAME" ]; then
    echo "Usage: $0 <build_dir> <profile_name> [output_file]"
    echo "Example: $0 deps/connectedhomeip/out/linux-arm64-light light"
    exit 1
fi

if [ ! -f "$BUILD_DIR/linked_objects.txt" ]; then
    echo "Error: $BUILD_DIR/linked_objects.txt not found."
    echo "Run docker/build.sh first to generate build manifests."
    exit 1
fi

if [ ! -f "$BUILD_DIR/linked_libs.txt" ]; then
    echo "Error: $BUILD_DIR/linked_libs.txt not found."
    exit 1
fi

# Read manifests
OBJECTS=$(cat "$BUILD_DIR/linked_objects.txt")
LIBS=$(cat "$BUILD_DIR/linked_libs.txt")

OBJ_COUNT=$(echo "$OBJECTS" | wc -l | tr -d ' ')
LIB_COUNT=$(echo "$LIBS" | wc -l | tr -d ' ')

echo "Generating $OUTPUT_FILE for profile: $PROFILE_NAME"
echo "  Objects: $OBJ_COUNT, Libraries: $LIB_COUNT"

# Detect the example app and common directory from the build output
# Object files contain paths like .../examples/<app>/<common>/...
EXAMPLE_APP=$(echo "$OBJECTS" | grep -o 'examples/[^/]*' | head -1 | sed 's|examples/||')
COMMON_DIR=$(echo "$OBJECTS" | grep -o 'examples/[^/]*/[^/]*-common' | head -1 | sed 's|examples/[^/]*/||')

if [ -z "$EXAMPLE_APP" ]; then
    echo "Warning: Could not detect example app from object files"
    EXAMPLE_APP="lighting-app"
fi
if [ -z "$COMMON_DIR" ]; then
    echo "Warning: Could not detect common dir from object files"
    COMMON_DIR="lighting-common"
fi

echo "  Example: $EXAMPLE_APP, Common: $COMMON_DIR"

# Generate the .mk file
cat > "$OUTPUT_FILE" << 'HEADER'
# Matter SDK Include Paths
# Auto-generated by scripts/gen_matter_includes.sh — do not edit manually
# Supports both host and cross-compilation builds

MATTER_SDK_ROOT = $(shell pwd)/deps/connectedhomeip
HEADER

# Write profile metadata
cat >> "$OUTPUT_FILE" << EOF

# Device profile: $PROFILE_NAME
# Example app: $EXAMPLE_APP
# Common target: $COMMON_DIR
MATTER_PROFILE_NAME = $PROFILE_NAME
EOF

# Write platform detection (parameterized with profile name)
cat >> "$OUTPUT_FILE" << EOF

# Detect target platform dynamically
ifeq (\$(CROSSCOMPILE),1)
    ifeq (\$(findstring aarch64,\$(TARGET_ARCH)),aarch64)
        MATTER_TARGET = linux-arm64-${PROFILE_NAME}
    else ifeq (\$(findstring arm,\$(TARGET_ARCH)),arm)
        MATTER_TARGET = linux-arm-${PROFILE_NAME}
    else
        MATTER_TARGET = linux-x64-${PROFILE_NAME}
    endif
else
    UNAME_S := \$(shell uname -s)
    UNAME_M := \$(shell uname -m)

    ifeq (\$(UNAME_S),Darwin)
        ifeq (\$(UNAME_M),arm64)
            MATTER_TARGET = darwin-arm64-${PROFILE_NAME}
        else
            MATTER_TARGET = darwin-x64-${PROFILE_NAME}
        endif
    else ifeq (\$(UNAME_S),Linux)
        ifeq (\$(UNAME_M),aarch64)
            MATTER_TARGET = linux-arm64-${PROFILE_NAME}
        else ifeq (\$(UNAME_M),armv7l)
            MATTER_TARGET = linux-arm-${PROFILE_NAME}
        else
            MATTER_TARGET = linux-x64-${PROFILE_NAME}
        endif
    else
        MATTER_TARGET = linux-x64-${PROFILE_NAME}
    endif
endif

MATTER_BUILD_DIR = \$(MATTER_SDK_ROOT)/out/\$(MATTER_TARGET)

# Required defines for Matter SDK headers
MATTER_DEFINES = -DCHIP_HAVE_CONFIG_H=1 -DNDEBUG
ifeq (\$(MATTER_DEBUG),1)
    MATTER_DEFINES += -DCHIP_CONFIG_VERBOSE_VERIFY_OR_DIE=1
endif
EOF

# Write include paths (profile-aware)
cat >> "$OUTPUT_FILE" << EOF

# Generated includes from build (MUST come first so config headers override defaults)
MATTER_INCLUDES = \\
    -I\$(MATTER_BUILD_DIR)/gen/include \\
    -I\$(MATTER_BUILD_DIR)/gen \\
    -I\$(MATTER_BUILD_DIR)/gen/third_party/connectedhomeip/examples/${EXAMPLE_APP}/${COMMON_DIR} \\
    -I\$(MATTER_BUILD_DIR)/gen/third_party/connectedhomeip/examples/${EXAMPLE_APP}/${COMMON_DIR}/zapgen

# Pre-generated ZAP headers (app-common cluster definitions)
MATTER_INCLUDES += \\
    -I\$(MATTER_SDK_ROOT)/zzz_generated/app-common

# Core Matter SDK includes
MATTER_INCLUDES += \\
    -I\$(MATTER_SDK_ROOT)/src \\
    -I\$(MATTER_SDK_ROOT)/src/include \\
    -I\$(MATTER_SDK_ROOT)/config/standalone \\
    -I\$(MATTER_SDK_ROOT)/examples \\
    -I\$(MATTER_SDK_ROOT)/examples/platform/linux \\
    -I\$(MATTER_SDK_ROOT)/examples/providers \\
    -I\$(MATTER_SDK_ROOT)/examples/${EXAMPLE_APP}/${COMMON_DIR}/include \\
    -I\$(MATTER_SDK_ROOT)/examples/common/tracing

# Third-party includes
MATTER_INCLUDES += \\
    -I\$(MATTER_SDK_ROOT)/third_party/nlassert/repo/include \\
    -I\$(MATTER_SDK_ROOT)/third_party/nlio/repo/include \\
    -I\$(MATTER_SDK_ROOT)/third_party/nlfaultinjection/include \\
    -I\$(MATTER_SDK_ROOT)/third_party/jsoncpp/repo/include \\
    -I\$(MATTER_SDK_ROOT)/third_party/boringssl/repo/src/include \\
    -I\$(MATTER_SDK_ROOT)/third_party/inipp/repo/inipp \\
    -I\$(MATTER_SDK_ROOT)/third_party/perfetto/repo/sdk \\
    -I\$(MATTER_SDK_ROOT)/src/tracing/perfetto/include

# Pigweed includes
PIGWEED_ROOT = \$(MATTER_SDK_ROOT)/third_party/pigweed/repo
MATTER_INCLUDES += \\
    -I\$(PIGWEED_ROOT)/pw_assert/public \\
    -I\$(PIGWEED_ROOT)/pw_assert/assert_compatibility_public_overrides \\
    -I\$(PIGWEED_ROOT)/pw_base64/public \\
    -I\$(PIGWEED_ROOT)/pw_bytes/public \\
    -I\$(PIGWEED_ROOT)/pw_containers/public \\
    -I\$(PIGWEED_ROOT)/pw_function/public \\
    -I\$(PIGWEED_ROOT)/pw_log/public \\
    -I\$(PIGWEED_ROOT)/pw_metric/public \\
    -I\$(PIGWEED_ROOT)/pw_numeric/public \\
    -I\$(PIGWEED_ROOT)/pw_polyfill/public \\
    -I\$(PIGWEED_ROOT)/pw_preprocessor/public \\
    -I\$(PIGWEED_ROOT)/pw_result/public \\
    -I\$(PIGWEED_ROOT)/pw_span/public \\
    -I\$(PIGWEED_ROOT)/pw_status/public \\
    -I\$(PIGWEED_ROOT)/pw_string/public \\
    -I\$(PIGWEED_ROOT)/pw_tokenizer/public \\
    -I\$(PIGWEED_ROOT)/pw_toolchain/public \\
    -I\$(PIGWEED_ROOT)/pw_varint/public \\
    -I\$(PIGWEED_ROOT)/third_party/fuchsia/repo/sdk/lib/stdcompat/include
EOF

# Write extra object files
echo "" >> "$OUTPUT_FILE"
echo "# Extra object files from $EXAMPLE_APP build (not in libCHIP.a)" >> "$OUTPUT_FILE"
echo "MATTER_EXTRA_OBJS = \\" >> "$OUTPUT_FILE"

FIRST=true
echo "$OBJECTS" | while IFS= read -r obj; do
    [ -z "$obj" ] && continue
    if [ "$FIRST" = true ]; then
        echo "    \$(MATTER_BUILD_DIR)/$obj \\" >> "$OUTPUT_FILE"
        FIRST=false
    else
        echo "    \$(MATTER_BUILD_DIR)/$obj \\" >> "$OUTPUT_FILE"
    fi
done

# Remove trailing backslash from last line
sed -i.bak '$ s/ \\$//' "$OUTPUT_FILE" && rm -f "${OUTPUT_FILE}.bak"

# Write static libraries
echo "" >> "$OUTPUT_FILE"
echo "# Matter SDK static libraries" >> "$OUTPUT_FILE"
echo "MATTER_STATIC_LIBS = \\" >> "$OUTPUT_FILE"

echo "$LIBS" | while IFS= read -r lib; do
    [ -z "$lib" ] && continue
    echo "    \$(MATTER_BUILD_DIR)/$lib \\" >> "$OUTPUT_FILE"
done

# Remove trailing backslash
sed -i.bak '$ s/ \\$//' "$OUTPUT_FILE" && rm -f "${OUTPUT_FILE}.bak"

# Write MATTER_LIBS and platform-specific libraries
cat >> "$OUTPUT_FILE" << 'EOF'

MATTER_LIBS = -Wl,--start-group $(MATTER_STATIC_LIBS) -Wl,--end-group

# Platform-specific libraries
ifeq ($(shell uname -s),Darwin)
    ifeq ($(CROSSCOMPILE),1)
        # Cross-compiling from Darwin to Linux (Nerves)
        MATTER_LIBS += -latomic -ldl -lpthread -lrt -lssl -lcrypto -lgio-2.0 -lgobject-2.0 -lglib-2.0
    else
        # Native Darwin build - no --start-group support, use single lib
        MATTER_LIBS = -L$(MATTER_BUILD_DIR)/lib -lCHIP
        MATTER_LIBS += -framework CoreFoundation -framework CoreBluetooth -framework IOKit -framework Security
    endif
else
    # Linux host or target
    MATTER_LIBS += -latomic -ldl -lpthread -lrt -lssl -lcrypto -lgio-2.0 -lgobject-2.0 -lglib-2.0
endif

# Cross-compilation sysroot includes (D-Bus, GLib, BlueZ headers)
ifeq ($(CROSSCOMPILE),1)
    ifdef NERVES_SDK_SYSROOT
        MATTER_INCLUDES += -I$(NERVES_SDK_SYSROOT)/usr/include/dbus-1.0
        MATTER_INCLUDES += -I$(NERVES_SDK_SYSROOT)/usr/lib/dbus-1.0/include
        MATTER_INCLUDES += -I$(NERVES_SDK_SYSROOT)/usr/include/glib-2.0
        MATTER_INCLUDES += -I$(NERVES_SDK_SYSROOT)/usr/lib/glib-2.0/include
    endif
endif
EOF

echo "Generated $OUTPUT_FILE successfully"
